name: capstone_margin_analysis

profile: capstone_template

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<dataset_name>_raw'
  capstone_margin_analysis:
    +dataset: raw

models:
  capstone_margin_analysis:
    +static_analysis: strict
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table